version: 1.0.0-beta6-{build}

image: Visual Studio 2017

configuration: Release

assembly_info:

  patch: true

  file: '**\AssemblyInfo.*'

  assembly_version: '{version}'

  assembly_file_version: '{version}'

  assembly_informational_version: '{version}'

dotnet_csproj:

  patch: true

  file: '**\*.csproj'

  version: '{version}'

  package_version: '{version}'

skip_commits:
  files:
    - appveyor*
    - '*gitignore'
    - '**/*.md'

services: mssql2016

before_build:

- cmd: dotnet restore src\

build:

  project: src\DominoEventStore\DominoEventStore.csproj

  verbosity: quiet

test_script:

- cmd: >-

    cd src/tests

    dotnet test

artifacts:

- path: '**\Release\**\*.nupkg'

  name: nuget

deploy:

- provider: NuGet

  api_key:

    secure: zSSdZy/TonHwA3Ltpb2LbBy5zD8+YfYFBayFHPSlkUwR2bj5L9/1MSpMVCqPCCwj
